# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: double-quote-string-fixer
# Update requirements.txt
-   repo: local
    hooks:
    -   id: update-requirements-txt
        name: update-requirements-txt
        description: 'Generate requirements.txt based on poetry.lock'
        entry: poetry
        args: [ export, --format, requirements.txt, --output, requirements.txt ]
        language: system
        pass_filenames: false
# autopep8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: ['--in-place', '--experimental']
# autoflake
-   repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--expand-star-imports',
          '--ignore-init-module-imports',
        ]
# isort
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        additional_dependencies: [ toml ]
# Remove print statements
- repo: https://github.com/dhruvmanila/remove-print-statements
  rev: 'v0.5.2'  # Replace with latest tag on GitHub
  hooks:
  - id: remove-print-statements
    # args: ['--verbose']   # Show all the print statements to be removed
